
default: &default
  adapter: postgresql
  encoding: unicode
  username: lucas
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_development

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample_production
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
